sudo: required
dist: trusty
env:
  global:
    - CODECLIMATE_REPO_TOKEN=$CC_TEST_REPORTER_ID
    - CODACY_ACCOUNT_TOKEN=$CODACY_ACCOUNT_TOKEN
    - CODACY_PROJECT_TOKEN=$CODACY_PROJECT_TOKEN
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - stable
before_install:
  - npm i npm@^4 -g
  - npm i codecov -g
  - npm i codeclimate-test-reporter -g
  - npm install codacy-coverage -g
  - npm install -g greenkeeper-lockfile@1
  - cd src/ngx-smart-modal
install:
  - npm install
script:
  - npm run test
  - npm run build
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - greenkeeper-lockfile-update
after_script:
  - greenkeeper-lockfile-upload
after_success:
  - codecov -t $CODECOV_TOKEN
  - codeclimate-test-reporter < 'coverage/lcov.info'
  - cat coverage/lcov.info | codacy-coverage
  - rm -r node_modules
  - cd ../..
  - npm run ghpages
notifications:
  email: false
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $PUSH_TOKEN
  on:
    branch: master
